# Generated by Django 3.0.7 on 2020-07-14 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SanitationHub', '0012_auto_20200117_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SanitationHub.Organisation'),
        ),
    ]
